  [[main]]
  identifier = "home"
  name = "Startseite"
  weight = 100
  url = "/"

  [[main]]
  identifier = "portfolio"
  name = "Portfolio"
  weight = 200
  url = "/portfolio/"
  
  [[main]]
  identifier = "blog"
  name = "Blog"
  weight = 300
  url = "/blog/"  

  [[main]]
  identifier = "about"
  name = "Über mich"
  weight = 400
  url = "/about/"
  
  [[main]]
  identifier = "contact"
  name = "Kontakt"
  weight = 500
  url = "/contact/"

  [[footer]]
  identifier = "impressum"
  name = "Impressum"
  weight = 1
  url = "/imprint/"